name = "VirialUEG"
uuid = "606fb3a7-65ae-406d-8718-9f45bebeccf6"
authors = ["Biplab Mahato"]
version = "1.0.0-DEV"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
